title: Smart Operating Block process documentation
description: Website with the Smart Operating Block process documentation
remote_theme: pmarsceill/just-the-docs
url: https://smartoperatingblock.github.io/documentation
color_scheme: "light"
aux_links:
  GitHub Organization: https://github.com/smartoperatingblock
search_enabled: true
logo: "/imgs/banner.png"
